In [1]:
import numpy as np
import pandas as pd
from gboosting import XGBTreeModel
import xgboost as xgb

In [2]:
X = np.random.randint(10, size=(5, 3))
y = np.random.randint(2, size=(5,))

In [ ]:
from tree import Tree, _Node

tree = Tree(max_depth=4)
tree.fit(X, y)

In [4]:
tree.predict(X)

array([1., 1., 0., 1., 1.])

In [5]:
my_gbm = XGBTreeModel(n_estimators=50)
my_gbm.fit(X, y, verbose=True)

100%|██████████| 50/50 [00:00<00:00, 960.74it/s]


In [6]:
my_gbm.predict(X)

array([ 0.55555556,  0.55555556, -0.55555556,  0.55555556,  0.55555556])

In [49]:
def parse_monks(filename):
    data = pd.read_csv(filename, sep=' ', header=None, skipinitialspace=True)
    data = data.iloc[:,:-1] 
    y = data[0].values
    X = pd.get_dummies(data.drop(0,axis=1),
                       columns=[1,2,3,4,5,6]).values.astype(int)
    return X, y


In [50]:
X, y = parse_monks('datasets/Monks/monks-1.train')

In [58]:
my_gbm = XGBTreeModel(n_estimators=15, max_depth=8, eta=0.5, lmbda=0.25)
my_gbm.fit(X, y, verbose=True)

100%|██████████| 15/15 [00:00<00:00, 63.17it/s]


In [60]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
my_gbm.predict(X)

array([ 0.99996948,  0.99996948,  0.99996948,  0.99996948,  0.99996948,
        0.99996948,  0.99996948,  0.99996948,  0.99996948,  0.99996948,
       -0.99996948, -0.99996948, -0.99996948,  0.99996948, -0.99996948,
       -0.99996948, -0.99996948, -0.99996948, -0.99996948, -0.99996948,
       -0.99996948, -0.99996948, -0.99996948, -0.99996948, -0.99996948,
       -0.99996948, -0.99996948, -0.99996948, -0.99996948, -0.99996948,
        0.99996948, -0.99996948, -0.99996948, -0.99996948, -0.99996948,
       -0.99996948,  0.99996948, -0.99996948, -0.99996948, -0.99996948,
       -0.99996948,  0.99996948, -0.99996948, -0.99996948, -0.99996948,
       -0.99996948, -0.99996948,  0.99996948,  0.99996948, -0.99996948,
       -0.99996948, -0.99996948, -0.99996948, -0.99996948, -0.99996948,
       -0.99996948, -0.99996948, -0.99996948, -0.99996948, -0.99996948,
       -0.99996948,  0.99996948,  0.99996948,  0.99996948,  0.99996948,
        0.99996948,  0.99996948,  0.99996948,  0.99996948,  0.99